### PR TITLE
Adding @param for CommandLauncher(...)

### PR DESCRIPTION
**Pull request by jsoref**
This doesn't conflict with #5 / #6

### CODE REVIEW

**Comment by jsoref** [comment]
@jglick : I mostly wanted to get rid of the complaint about the lack of javadoc, and since I was there, it seemed like I might as well make the doc useful instead of "This is an x".

**Comment by jsoref** [comment]
@jglick: I updated the html

**Comment by oleg-nenashev** [comment]
Will ship it once the Release Drafter PR is accepted

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/command-launcher-plugin/releases/tag/command-launcher-1.4 , thanks @jsoref !

**Pull request merged**
