### PR TITLE
Refresh plugin for April 2023

### PR DESCRIPTION
**Pull request by basil**
This is required for https://github.com/jenkinsci/stapler/pull/452 so that tests continue passing in this plugin and in BOM.

### CODE REVIEW

**Comment by basil** [comment]
Used my admin powers to replay the build with the `Jenkinsfile` changes here: https://ci.jenkins.io/job/Plugins/job/command-launcher-plugin/job/PR-79/2/

**Comment by basil** [comment]
@jenkinsci/command-launcher-plugin-developers Can this please be merged & released?

**Comment by jglick** [comment]
https://github.com/jenkinsci/command-launcher-plugin/releases/tag/100.v2f6722292ee8

**Comment by basil** [comment]
Thank you!

**Pull request merged**
